package net.rim.device.internal.applicationcontrol;

public class ApplicationControlConstants {
   public static final int MODULE_HASH_LENGTH;
   public static final byte[] EMPTY_HASH;
   public static final byte[] FILLED_HASH;
   public static final int REQUIRED_FLAG;
   public static final int EXCLUDED_FLAG;
   public static final int IPC_ALLOWED_FLAG;
   public static final int INTERNAL_ALLOWED_FLAG;
   public static final int INTERNAL_PROMPT_FLAG;
   public static final int EXTERNAL_ALLOWED_FLAG;
   public static final int EXTERNAL_PROMPT_FLAG;
   public static final int LOCAL_ALLOWED_FLAG;
   public static final int PHONE_ALLOWED_FLAG;
   public static final int PHONE_PROMPT_FLAG;
   public static final int EMAIL_ALLOWED_FLAG;
   public static final int PIM_ALLOWED_FLAG;
   public static final int BROWSER_FILTERS_FLAG;
   public static final int EVENT_INJECTOR_FLAG;
   public static final int BLUETOOTH_SERIAL_PROFILE_ALLOWED_FLAG;
   public static final int HANDHELD_KEY_STORE_ALLOWED_FLAG;
   public static final int KEY_STORE_MEDIUM_SECURITY_ALLOWED_FLAG;
   public static final int LAPI_ALLOWED_FLAG;
   public static final int LAPI_PROMPT_FLAG;
   public static final int THEME_DATA_ALLOWED_FLAG;
   public static final int AUTHENTICATOR_API_ALLOWED_FLAG;
   public static final int FILE_API_ALLOWED_FLAG;
   public static final int CMM_API_ALLOWED_FLAG;
   public static final int DEVICE_SETTINGS_ALLOWED_FLAG;
   public static final int DEVICE_SETTINGS_PROMPT_FLAG;
   public static final int SCREEN_CAPTURE_ALLOWED_FLAG;
   public static final int SCREEN_CAPTURE_PROMPT_FLAG;
   public static final int WIFI_ALLOWED_FLAG;
   public static final int WIFI_PROMPT_FLAG;
   public static final int IDLE_TIMER_ALLOWED_FLAG;
   public static final int IDLE_TIMER_PROMPT_FLAG;
   public static final int MEDIA_ALLOWED_FLAG;
   public static final int MEDIA_PROMPT_FLAG;
   public static final byte TAG_DOMAIN_INTERNAL_CONNECTIONS;
   public static final byte TAG_DOMAIN_EXTERNAL_CONNECTIONS;
   public static final byte TAG_DOMAIN_BROWSER_FILTERS;
   static final long FLAG;
   static final int RRI_BYPASS_FLAG;
   static final long ALL_FLAGS_MASK;
   public static final long ALLOW_FLAGS_MASK;
   public static final long PAIRED_ALLOW_FLAGS_MASK;
   public static final long NON_USER_FLAGS_MASK;
   public static final long RESTRICTIVE_SETTINGS_MASK;
   public static final long PERMISSIVE_SETTINGS_MASK;
   static final long INVERTED_SYNC_FLAGS;
   public static int[] APP_PERM_TO_APP_CONTROL_MAP;
}
